### ISSUE TITLE
多客户端网络日记（可打印某个客户端历史记录）

### ISSUE THREAD

**Issue by junjielizero** [junjielizero/OMOOC2py#2]
# 效果
* 能实现附加题效果，但目前仅限于两个客户端，后续优化思路见下：

* 效果示意图：

<img width="1250" alt="2015-11-05 9 44 42" src="https://github-cloud.s3.amazonaws.com/assets%2F14881664%2F10957778%2F89af6a40-83a2-11e5-8664-159521094f90.png">

**Comment by junjielizero** [comment]
# 思路：

## 现有思路：
* 不同客户端配有对应的记录文件，所有记录保存在另一个文件，每次运行客户端脚本就可以打印不同的记录
* 预先在client1.py,client2.py，分别预先设定client1，client2变量，用于标识不同客户端输入的内容，通过列表['client1','内容']，发送'client1'、'内容'两个元素
* server.py接收具有标识的日记输入内容：由于服务器每次只能接收一次消息，在while循环下，利用列表存储标识与内容，具有标识的内容分别对应不同的文件存储

## 现有思路问题：
1.  若客户端特别多（如200人），“不同客户端配有对应记录文件”方法会有很大问题，首先每个客户端脚本要大改动，如打开文件之类
2.  如果要新增客户端，目前脚本并不能提供创建方法

## 后续改进思路（初步）：
1.  延续客户端发送标识的内容思路
2.  放弃“不同客户端配有对应记录文件”方法，改用字典结构输出不同客户端的输入记录，具体如下：
* 服务端存储所有客户端历史记录（但具有标识，在txt文件内）
* 将txt内容输送到列表，效果为['client1',['a','b'],'client2',['c','d' ]……]，最终将客户端标识物（如client1）作为字典Key，接着的列表元素为value（输入内容预先变为列表结构），最终的字典结构{'client1':['a',''b],'client2':['c','d']}
3. 选择性打印：输入指定key,即可打印对应的客户端历史记录
4. 新建客户端与标识物设置：每次新建客户端，用户都输入该客户端名字，而该文字为该客户端的标识物

**Comment by junjielizero** [comment]
上面写的有点乱，若有不明白的，欢迎留言

**Comment by bambooom** [comment]
字典结构似乎不错，这个我还不是很熟也不是很会用，嗯， 要自己补下~
但是我在想你现在是client1.py client2.py只能有两个客户端是吧，那么应该可以把client包装成一个class，那就很容易量产了。。。
