### ISSUE TITLE
5w 公共网页笔记

### ISSUE THREAD

**Issue by junjielizero** [junjielizero/OMOOC2py#3]

**Comment by junjielizero** [comment]
# 疑问：
* 客户端打印历史记录，是否真的需要BeautifulSoup来解析html网页，不能像4w那样打开本地文件——即将kvdb数据存储于本地文件（该文件格式后续是.kvdb吗？）。尝试[这里](https://www.sinacloud.com/doc/sae/python/tools.html#kvdb)方法，但一直不成功。

# 感想：
* 这次做的作业虽完成，但不太满意，主要在于：

1. 不熟悉html语言，在这模块花了太多时间，看了之前提交童鞋做的内容，才明白怎么写好html文档和BeautifulSoup
2. 这周没太多时间完成tab和后台监控笔记之类的功能，之后再补上

**Comment by junjielizero** [comment]
@bambooom  kvdb列表排序可看[这个](http://stackoverflow.com/questions/33782035/how-can-i-sort-my-number-list-in-python)，就可以按顺序搞掂了

另外，真的需要BeatuifulSoup来解析页面吗？是不是我们想多了

**Comment by bambooom** [comment]
噢噢~多谢！
BeautifulSoup我觉得很方便是因为可以直接提取html tag里面的内容，而且后面我才学习到html 的tag还可以编class，BeautifulSoup也可以直接根据class来提取，所以很方便。
我一开始也是没有用它的，就想了很蠢的办法用re去寻找pattern，再去掉不要的部分。。。。不是做不到，就觉得自己在这个上面浪费了很多时间，但其实用soup就很容易了。

**Comment by wp-lai** [comment]
> 真的需要BeatuifulSoup来解析页面吗？

其实可以开放API给CLI，例如server中添一个route('/cli/note')，返回日记信息，然后CLI对这个url发起get请求就行

**Comment by junjielizero** [comment]
@wp-lai 其实我在想利用本地同步的KVDB.pkl将网页端数据保存，然后命令行打印结果调用的是kvdb.pkl数据，做法与1w本地存储文件思路一样
